name: Node.js CI

on:
  push:
    paths:
      - 'node/**'
      - '.github/workflows/node.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
        working-directory: node
      - run: npm run scan-cves
        working-directory: node

  static_code_analysis:
    runs-on: ubuntu-latest
    name: Horusec Scan
    steps:
      - name: Run Horusec
        id: run_horusec
        uses: fike/horusec-action@v0.2.1
        with:
          arguments: --project-path "./node" --ignore "node_modules/**, whitelist.json, package.json, package-lock.json"