name: Scala CI

on:
  push:
    paths:
      - 'scala/**'
      - '.github/workflows/scala.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 8
    - name: Build and Test
      run: sbt -v +test
      working-directory: scala
    - name: Scan for CVEs
      run: sbt dependencyCheck
      working-directory: scala

  static_code_analysis:
    runs-on: ubuntu-latest
    name: Horusec Scan
    steps:
      - name: Run Horusec
        id: run_horusec
        uses: fike/horusec-action@v0.2.1
        with:
          # arguments: -p="./scala"
          arguments: -p="./scala" --config-file-path="horusec-config.json"